site_name: Campamento IOI 2023

nav:
  - Día 1:
    - Complejidad: dia-1/complejidad.md
    - Búsqueda binaria: dia-1/busqueda_binaria.md
    - STL: dia-1/stl.md
  - Día 2:
    - Resolución Contest 1: dia-2/resolucion_contest_1.md
    - Grafos 1: dia-2/grafos_1.md
  - Día 3:
    - Resolución Contest 2: dia-3/resolucion_contest_2.md
    - Grafos 2: dia-3/DP.md
  - Día 4:
    - Resolución Contest 3: dia-4/resolucion_contest_3.md
    - Struct: dia-4/struct.md
  - Apéndice:
    - Logaritmos: apendice/logaritmos.md
    - Problema parentesis balanceados: apendice/problema_parentesis_balanceados.md

theme:
  name: material
  language: en
  font:
    text: Open Sans
  features:
    - navigation.indexes
    - content.code.annotate

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/images.css