site_name: Campamento IOI 2023

nav:
  - Dia 1:
    - Complejidad: dia-1/complejidad.md
    - Búsqueda binaria: dia-1/busqueda_binaria.md
    - STL: dia-1/stl.md
  - Apéndice:
    - Logaritmos: apendice/logaritmos.md

theme:
  name: material
  language: en
  font:
    text: Open Sans
  features:
    - navigation.indexes
    - content.code.annotate

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
