site_name: Campamento OCI 2023

nav:
  - Dia 1:
    - Complejidad: day_1/complexity.md
    - Búsqueda binaria: day_1/binary_search.md
    - STL: day_1/stl.md
  - Apéndice: appendix/index.md

theme:
  name: material
  features:
    - navigation.indexes
    - content.code.annotate
  language: en

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
